# Generated by Django 3.0.5 on 2024-11-24 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_dealer_operator_repairworker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Operator',
            new_name='TractorOperator',
        ),
    ]
