# Generated by Django 3.0.5 on 2024-11-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20241125_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='tractoroperator',
            name='operator_application_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
